### ISSUE TITLE
Running without a GPU error

### ISSUE THREAD

**Issue by ivoras** [alexjc/neural-doodle#10]
This is on a VM, without a GPU.

```
vm:~/neural-doodle> python3 doodle.py --style samples/Monet.jpg --output samples/Coastline.png\
?                   --device=cpu --iterations=40
Neural Doodle for semantic style transfer.
/usr/local/lib/python3.4/dist-packages/theano/tensor/signal/downsample.py:5: UserWarning: downsample module has been moved to the pool module.
  warnings.warn("downsample module has been moved to the pool module.")
  - Loading content semantic map from samples/Coastline_sem.png.
  - Loading style image data from samples/Monet.jpg.
  - Loading style semantic map from samples/Monet_sem.png.

Phase #0: resolution 128x96  scale 0.25
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/op.py", line 912, in rval
    r = p(n, [x[0] for x in i], o)
  File "/usr/local/lib/python3.4/dist-packages/theano/tensor/nnet/abstract_conv.py", line 469, in perform
    'AbstractConv2d theano optimization failed. '
NotImplementedError: AbstractConv2d theano optimization failed. Did you exclude both "conv_dnn" and "conv_gemm" from the optimizer? Is cudnn available and does the GPU support it?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "doodle.py", line 462, in <module>
    generator.run()
  File "doodle.py", line 422, in run
    self.prepare_style(scale)
  File "doodle.py", line 261, in prepare_style
    result = extractor(self.style_image, self.style_map)
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python3.4/dist-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/op.py", line 912, in rval
    r = p(n, [x[0] for x in i], o)
  File "/usr/local/lib/python3.4/dist-packages/theano/tensor/nnet/abstract_conv.py", line 469, in perform
    'AbstractConv2d theano optimization failed. '
NotImplementedError: AbstractConv2d theano optimization failed. Did you exclude both "conv_dnn" and "conv_gemm" from the optimizer? Is cudnn available and does the GPU support it?
Apply node that caused the error: AbstractConv2d{border_mode=(1, 1), subsample=(1, 1), filter_flip=True, imshp=(1, 3, None, None), kshp=(64, 3, 3, 3)}(<TensorType(float32, 4D)>, W)
Toposort index: 14
Inputs types: [TensorType(float32, 4D), TensorType(float32, 4D)]
Inputs shapes: [(1, 3, 96, 128), (64, 3, 3, 3)]
Inputs strides: [(0, 4, 1536, 12), (108, 36, 12, 4)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Elemwise{Composite{(i0 * (Abs((i1 + i2)) + i1 + i2))}}[(0, 1)](TensorConstant{(1, 1, 1, 1) of 0.5}, AbstractConv2d{border_mode=(1, 1), subsample=(1, 1), filter_flip=True, imshp=(1, 3, None, None), kshp=(64, 3, 3, 3)}.0, InplaceDimShuffle{x,0,x,x}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "doodle.py", line 462, in <module>
    generator.run()
  File "doodle.py", line 420, in run
    self.model.setup(layers=['sem'+l for l in self.style_layers] + ['conv'+l for l in self.content_layers])
  File "doodle.py", line 154, in setup
    outputs = lasagne.layers.get_output([self.network[l] for l in layers], self.tensor_inputs)
  File "/usr/local/lib/python3.4/dist-packages/lasagne/layers/helper.py", line 191, in get_output
    all_outputs[layer] = layer.get_output_for(layer_inputs, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/lasagne/layers/conv.py", line 257, in get_output_for
    conved = self.convolve(input, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/lasagne/layers/conv.py", line 535, in convolve
    filter_flip=self.flip_filters)

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

```

**Comment by alexjc** [comment]
Thanks. Did you also try without the VM?

**Comment by ikkebr** [comment]
This is a problem with Blas.

**Comment by alexjc** [comment]
So just `apt-get install` it?

**Comment by ikkebr** [comment]
Installing libblas-dev and libopenblas-dev solved this problem for me

**Comment by alexjc** [comment]
Added in the `README.rst` into troubleshooting.
https://github.com/alexjc/neural-doodle#troubleshooting-problems
