### ISSUE TITLE
Can't understand the exceptions

### ISSUE THREAD

**Issue by oiale** [alexjc/neural-doodle#106]
Hey, I get following error output when trying to run doodle.py 
```
C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\lasagne\layers\pool.py:266: UserWarning: DEPRECATION: the 'ds' parameter is not going to exist anymore as it is going to be replaced by the parameter 'ws'.
  mode=self.mode,
C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\lasagne\layers\pool.py:266: UserWarning: DEPRECATION: the 'st' parameter is not going to exist anymore as it is going to be replaced by the parameter 'stride'.
  mode=self.mode,
C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\lasagne\layers\pool.py:266: UserWarning: DEPRECATION: the 'padding' parameter is not going to exist anymore as it is going to be replaced by the parameter 'pad'.
  mode=self.mode,
ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: InplaceDimShuffle{x,x,x,x}(TensorConstant{2.0})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\theano\gof\cmodule.py", line 1784, in _try_compile_tmp
    os.remove(exe_path + ".exe")
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\ILLYAS~1\\AppData\\Local\\Temp\\try_march_zjxkpyah.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\theano\gof\opt.py", line 1957, in process_node
    replacements = lopt.transform(node)
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\theano\tensor\opt.py", line 6387, in constant_folding
    no_recycling=[], impl=impl)
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\theano\gof\op.py", line 924, in make_thunk
    no_recycling)
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\theano\gof\op.py", line 828, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\theano\gof\cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\theano\gof\cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\theano\gof\cc.py", line 1578, in cthunk_factory
    key = self.cmodule_key()
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\theano\gof\cc.py", line 1268, in cmodule_key
    compile_args=self.compile_args(),
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\theano\gof\cc.py", line 951, in compile_args
    ret += c_compiler.compile_args()
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\theano\gof\cmodule.py", line 2088, in compile_args
    default_compilation_result, default_execution_result = try_march_flag(GCC_compiler.march_flags)
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\theano\gof\cmodule.py", line 1856, in try_march_flag
    flags=cflags, try_run=True)
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\theano\gof\cmodule.py", line 2188, in try_compile_tmp
    comp_args)
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\theano\gof\cmodule.py", line 1789, in _try_compile_tmp
    err += "\n" + str(e)
TypeError: can't concat bytes to str

C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\lasagne\layers\pool.py:266: UserWarning: DEPRECATION: the 'ds' parameter is not going to exist anymore as it is going to be replaced by the parameter 'ws'.
  mode=self.mode,
C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\lasagne\layers\pool.py:266: UserWarning: DEPRECATION: the 'st' parameter is not going to exist anymore as it is going to be replaced by the parameter 'stride'.
  mode=self.mode,
C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\lasagne\layers\pool.py:266: UserWarning: DEPRECATION: the 'padding' parameter is not going to exist anymore as it is going to be replaced by the parameter 'pad'.
  mode=self.mode,
Traceback (most recent call last):
  File "C:\Test\neural-doodle\doodle.py", line 658, in <module>
    generator.run()
  File "C:\Test\neural-doodle\doodle.py", line 635, in run
    iprint=-1)                       # Handle our own logging of information.
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\scipy\optimize\lbfgsb.py", line 193, in fmin_l_bfgs_b
    **opts)
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\scipy\optimize\lbfgsb.py", line 328, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\scipy\optimize\lbfgsb.py", line 278, in func_and_grad
    f = fun(x, *args)
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\scipy\optimize\optimize.py", line 292, in function_wrapper
    return function(*(wrapper_args + args))
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\scipy\optimize\optimize.py", line 63, in __call__
    fg = self.fun(x, *args)
  File "C:\Test\neural-doodle\doodle.py", line 536, in evaluate
    best_idx = self.evaluate_slices(f, l)
  File "C:\Test\neural-doodle\doodle.py", line 504, in evaluate_slices
    layer.W.set_value(weights)
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\theano\sandbox\cuda\var.py", line 156, in set_value
    self.container.value = value  # this will copy a numpy ndarray
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\theano\gof\link.py", line 477, in __set__
    **kwargs)
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\theano\sandbox\cuda\type.py", line 120, in filter_inplace
    strict, old_data)
TypeError: ('Non-unit size in broadcastable dimension 0', 'Container name "None"')
```

Could you please help me understand a bit more about the errors ? 

Specs: Win 8.1, VS 2013, python 3.4.4, Theano 0.9.0.dev4, Lasagne 0.2.dev1, GTX 1070, Cuda 8 + CudNN
theanorc : 
```
[global]
device=gpu
floatX=float32

[nvcc]
compiler_bindir=C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64
flags=--cl-version=2013

[dnn.conv]
algo_fwd = time_once
algo_bwd_data = time_once
algo_bwd_filter = time_once

[lib]
cnmem = .45
```

Some of the warnings are the change of API I suppose, but I am more interested in the errors and (possible) ways of fixing them.

**Comment by alexjc** [comment]
Try getting the version of Theano that's from `requirements.txt`. You seem out-of-date there!

**Comment by oiale** [comment]
I have Theano 0.9.0.dev4 which is >=0.8.1. I will try downgrading and see what happens.

**Comment by oiale** [comment]
Downgraded and still getting the same error. I am not sure if I need to downgrade something else.

**Comment by oiale** [comment]
Same error, but now on linux (Ubuntu 16, cuda 8)
All the libs were installed from requirements.txt
```
Traceback (most recent call last):
  File "doodle.py", line 658, in <module>
    generator.run()
  File "doodle.py", line 635, in run
    iprint=-1)                       # Handle our own logging of information.
  File "/home/user/.local/lib/python3.5/site-packages/scipy/optimize/lbfgsb.py", line 193, in fmin_l_bfgs_b
    **opts)
  File "/home/user/.local/lib/python3.5/site-packages/scipy/optimize/lbfgsb.py", line 328, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/home/user/.local/lib/python3.5/site-packages/scipy/optimize/lbfgsb.py", line 278, in func_and_grad
    f = fun(x, *args)
  File "/home/user/.local/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 292, in function_wrapper
    return function(*(wrapper_args + args))
  File "/home/user/.local/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 63, in __call__
    fg = self.fun(x, *args)
  File "doodle.py", line 536, in evaluate
    best_idx = self.evaluate_slices(f, l)
  File "doodle.py", line 504, in evaluate_slices
    layer.W.set_value(weights)
  File "/home/user/.local/lib/python3.5/site-packages/theano/sandbox/cuda/var.py", line 156, in set_value
    self.container.value = value  # this will copy a numpy ndarray
  File "/home/user/.local/lib/python3.5/site-packages/theano/gof/link.py", line 477, in __set__
    **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/theano/sandbox/cuda/type.py", line 120, in filter_inplace
    strict, old_data)
TypeError: ('Non-unit size in broadcastable dimension 0', 'Container name "None"')

```

**Comment by alexjc** [comment]
I had this issue as well. Please use the exact version of the dependencies is `requirements.txt` until someone has time to dig into this!

**Comment by oiale** [comment]
Then you should change requirements in requirements.txt from ">=" into "==".

**Comment by alexjc** [comment]
@oiale If you `pip install -r requirements.txt` it specifies the exact revision of Lasagne and works fine. On my machine, only if you `pip install Lasagne` does it fail.  Can you confirm?

**Comment by oiale** [comment]
Yes, lasagne version from req works fine. Thank you very much. Do you know what happened in the newer versions of Lasagne ?

**Comment by oiale** [comment]
I got another exception  (a different one). I hope it is not memory error
```
←[1;94mPhase #3: resolution 650x655  scale 1.0←[0;94m
  - Style layer 3_1: (29304, 256, 3, 3) patches in 67,516kb.
  - Style layer 4_1: (7154, 512, 3, 3) patches in 32,965kb.
  - Content layer conv4_2: 512 features in 3,359kb.
←[0m
Traceback (most recent call last):
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\theano\compile
\function_module.py", line 859, in __call__
    outputs = self.fn()
RuntimeError: Cuda error 'unspecified launch failure' while copying 4 data eleme
nt to device memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "doodle.py", line 658, in <module>
    generator.run()
  File "doodle.py", line 635, in run
    iprint=-1)                       # Handle our own logging of information.
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\scipy\optimize
\lbfgsb.py", line 193, in fmin_l_bfgs_b
    **opts)
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\scipy\optimize
\lbfgsb.py", line 328, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\scipy\optimize
\lbfgsb.py", line 278, in func_and_grad
    f = fun(x, *args)
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\scipy\optimize
\optimize.py", line 292, in function_wrapper
    return function(*(wrapper_args + args))
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\scipy\optimize
\optimize.py", line 63, in __call__
    fg = self.fun(x, *args)
  File "doodle.py", line 541, in evaluate
    grads, *losses = self.compute_grad_and_losses(current_img, self.content_map,
 *current_best)
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\theano\compile
\function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\theano\gof\lin
k.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\six.py", line
685, in reraise
    raise value.with_traceback(tb)
  File "C:\Tools\WinPython64\python-3.4.4.amd64\lib\site-packages\theano\compile
\function_module.py", line 859, in __call__
    outputs = self.fn()
RuntimeError: Cuda error 'unspecified launch failure' while copying 4 data eleme
nt to device memory
Apply node that caused the error: GpuFromHost(Elemwise{Cast{float32}}.0)
Toposort index: 249
Inputs types: [TensorType(float32, vector)]
Inputs shapes: [(4,)]
Inputs strides: [(4,)]
Inputs values: [array([  2.57600000e+04,   2.56000000e+02,   3.00000000e+00,
         3.00000000e+00], dtype=float32)]
Outputs clients: [[GpuSubtensor{int64}(GpuFromHost.0, Constant{3}), GpuSubtensor
{int64}(GpuFromHost.0, Constant{0}), GpuSubtensor{int64}(GpuFromHost.0, Constant
{1}), GpuSubtensor{int64}(GpuFromHost.0, Constant{2})]]

HINT: Re-running with most Theano optimization disabled could give you a back-tr
ace of when this node was created. This can be done with by setting the Theano f
lag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be
 disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storag
e map footprint of this apply node.

```

**Comment by oiale** [comment]
Ok, I got the answer to this one. Nvidia Nsight Monitor -> turn off WDDM TDR
