### ISSUE TITLE
"PyString_Check" redefined Error 

### ISSUE THREAD

**Issue by filmo** [alexjc/neural-doodle#107]
I'm running in a Anaconda Python 3 environment. Cuda 7.5 with CUDNN 5.1.3

I ran: python3 -m pip install --ignore-installed -r requirements.txt

When I try the sample:

python3 doodle.py --style samples/Renoir.jpg --output samples/Landscape.png --device=gpu0 --iterations=80

I'm getting a large code dump followed by the following sets of error:
```
Neural Doodle for semantic style transfer.
  - Using device `gpu0` for processing the images.
  - Loading content semantic map from samples/Landscape_sem.png.
  - Loading style image data from samples/Renoir.jpg.
  - Loading style semantic map from samples/Renoir_sem.png.

Phase #0: resolution 128x80  scale 0.25
1 #include <Python.h>
2 #include <iostream>
3 #include "theano_mod_helper.h"

*** Snip ***

821     PyObject *m = PyModule_Create(&moduledef);
822     return m;
823 }
824 
===============================
In file included from mod.cu:4:0:
/home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/theano/sandbox/cuda/cuda_ndarray.cuh:17:0: warning: "PyString_Check" redefined [enabled by default]
 #define PyString_Check PyUnicode_Check
 ^
In file included from /home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/theano/sandbox/cuda/cuda_ndarray.cuh:11:0,
                 from mod.cu:4:
/home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/numpy/core/include/numpy/npy_3kcompat.h:63:0: note: this is the location of the previous definition
 #define PyString_Check PyBytes_Check
 ^
In file included from mod.cu:4:0:
/home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/theano/sandbox/cuda/cuda_ndarray.cuh:18:0: warning: "PyString_FromString" redefined [enabled by default]
 #define PyString_FromString PyUnicode_FromString
 ^
In file included from /home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/theano/sandbox/cuda/cuda_ndarray.cuh:11:0,
                 from mod.cu:4:
/home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/numpy/core/include/numpy/npy_3kcompat.h:65:0: note: this is the location of the previous definition
 #define PyString_FromString PyBytes_FromString

** Snip **

/home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/numpy/core/include/numpy/npy_3kcompat.h:74:0: note: this is the location of the previous definition
 #define PyString_Size PyBytes_Size
 ^
mod.cu(70): error: argument of type "int" is incompatible with parameter of type "cudnnTensorFormat_t"
mod.cu(71): error: argument of type "const int *" is incompatible with parameter of type "int"
mod.cu(71): error: too few arguments in function call
mod.cu(572): error: argument of type "int" is incompatible with parameter of type "cudnnNanPropagation_t"
mod.cu(573): error: argument of type "int *" is incompatible with parameter of type "int"
mod.cu(573): error: too few arguments in function call
mod.cu(593): warning: subscript out of range
mod.cu(593): warning: subscript out of range
mod.cu(593): warning: subscript out of range
mod.cu(63): warning: function "c_set_filterNd" was declared but never referenced
6 errors detected in the compilation of "/tmp/tmpxft_00002050_00000000-9_mod.cpp1.ii".

['nvcc', '-shared', '-O3', '-arch=sm_52', '-m64', '-Xcompiler', '-fno-math-errno,-Wno-unused-label,-Wno-unused-variable,-Wno-write-strings,-DCUDA_NDARRAY_CUH=mc72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden', '-Xlinker', '-rpath,/home/philglau/.theano/compiledir_Linux-3.19--generic-x86_64-with-debian-jessie-sid-x86_64-3.5.2-64/cuda_ndarray', '-I/home/philglau/.theano/compiledir_Linux-3.19--generic-x86_64-with-debian-jessie-sid-x86_64-3.5.2-64/cuda_ndarray', '-I/usr/local/cuda-7.5/include', '-I/home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/theano/sandbox/cuda', '-I/home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/numpy/core/include', '-I/home/philglau/anaconda2/envs/doodle3/include/python3.5m', '-I/home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/theano/gof', '-o', '/home/philglau/.theano/compiledir_Linux-3.19--generic-x86_64-with-debian-jessie-sid-x86_64-3.5.2-64/tmplikw4yol/mcc3066e13c4a42f7e6525d2bc9532fa9.so', 'mod.cu', '-L/home/philglau/.theano/compiledir_Linux-3.19--generic-x86_64-with-debian-jessie-sid-x86_64-3.5.2-64/cuda_ndarray', '-L/home/philglau/anaconda2/envs/doodle3/lib', '-lcudart', '-lcublas', '-lcuda_ndarray', '-lcudnn', '-lpython3.5m']
Traceback (most recent call last):
  File "doodle.py", line 488, in <module>
    generator.run()
  File "doodle.py", line 443, in run
    self.prepare_style(scale)
  File "doodle.py", line 278, in prepare_style
    self.extract_patches([self.model.tensor_outputs['sem'+l] for l in self.style_layers]))
  File "/home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/theano/compile/function.py", line 320, in function
    output_keys=output_keys)
  File "/home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/theano/compile/pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "/home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/theano/compile/function_module.py", line 1777, in orig_function
    defaults)
  File "/home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/theano/compile/function_module.py", line 1641, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/theano/gof/link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/theano/gof/vm.py", line 1003, in make_all
    no_recycling))
  File "/home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/theano/sandbox/cuda/__init__.py", line 257, in make_thunk
    compute_map, no_recycling)
  File "/home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/theano/gof/op.py", line 970, in make_thunk
    no_recycling)
  File "/home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/theano/gof/op.py", line 879, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/theano/gof/cc.py", line 1200, in make_thunk
    keep_lock=keep_lock)
  File "/home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/theano/gof/cc.py", line 1143, in __compile__
    keep_lock=keep_lock)
  File "/home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/theano/gof/cc.py", line 1595, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/theano/gof/cmodule.py", line 1142, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/theano/gof/cc.py", line 1506, in compile_cmodule
    preargs=preargs)
  File "/home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/theano/sandbox/cuda/nvcc_compiler.py", line 396, in compile_str
    'for cmd', ' '.join(cmd))
Exception: ('The following error happened while compiling the node', GpuDnnPool{mode='average_exc_pad'}(GpuContiguous.0, TensorConstant{(2,) of 8}, TensorConstant{(2,) of 8}, TensorConstant{(2,) of 0}), '\n', 'nvcc return status', 2, 'for cmd', 'nvcc -shared -O3 -arch=sm_52 -m64 -Xcompiler -fno-math-errno,-Wno-unused-label,-Wno-unused-variable,-Wno-write-strings,-DCUDA_NDARRAY_CUH=mc72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden -Xlinker -rpath,/home/philglau/.theano/compiledir_Linux-3.19--generic-x86_64-with-debian-jessie-sid-x86_64-3.5.2-64/cuda_ndarray -I/home/philglau/.theano/compiledir_Linux-3.19--generic-x86_64-with-debian-jessie-sid-x86_64-3.5.2-64/cuda_ndarray -I/usr/local/cuda-7.5/include -I/home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/theano/sandbox/cuda -I/home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/numpy/core/include -I/home/philglau/anaconda2/envs/doodle3/include/python3.5m -I/home/philglau/anaconda2/envs/doodle3/lib/python3.5/site-packages/theano/gof -o /home/philglau/.theano/compiledir_Linux-3.19--generic-x86_64-with-debian-jessie-sid-x86_64-3.5.2-64/tmplikw4yol/mcc3066e13c4a42f7e6525d2bc9532fa9.so mod.cu -L/home/philglau/.theano/compiledir_Linux-3.19--generic-x86_64-with-debian-jessie-sid-x86_64-3.5.2-64/cuda_ndarray -L/home/philglau/anaconda2/envs/doodle3/lib -lcudart -lcublas -lcuda_ndarray -lcudnn -lpython3.5m', "[GpuDnnPool{mode='average_exc_pad'}(<CudaNdarrayType(float32, 4D)>, TensorConstant{(2,) of 8}, TensorConstant{(2,) of 8}, TensorConstant{(2,) of 0})]")
(doodle3) philglau (master) neural-doodle $ 
```

Seems like there's some conflict between a #define in cuda_ndarray.cuh and numpy_3kcompat.h ?? (I'm only guessing) Or perhaps mod.cu errors near line 70 & 573 are to blame?? 

Any thoughts?

(The CPU version seems to run in my Anaconda environment so the code problem seems related to CUDA in some way.)

**Comment by ArthurZC23** [comment]
It is related to the GPU. lasagne gives this error when working with CuDNN 5. Try to downgrade to version 4 or to disable it and see if it runs.
