### ISSUE TITLE
Error: Non-unit value on shape on a broadcastable dimension.

### ISSUE THREAD

**Issue by ssccsscc** [alexjc/neural-doodle#109]
I am tried to ran it on windows with cpu but it show error:
`Traceback (most recent call last):
  File "doodle.py", line 658, in <module>
    generator.run()
  File "doodle.py", line 635, in run
    iprint=-1)                       # Handle our own logging of information.
  File "C:\Lasagne\WinPython\python-3.4.4.amd64\lib\site-packages\scipy\optimize\lbfgsb.py", line 193, in fmin_l_bfgs_b
    **opts)
  File "C:\Lasagne\WinPython\python-3.4.4.amd64\lib\site-packages\scipy\optimize\lbfgsb.py", line 328, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "C:\Lasagne\WinPython\python-3.4.4.amd64\lib\site-packages\scipy\optimize\lbfgsb.py", line 278, in func_and_grad
    f = fun(x, *args)
  File "C:\Lasagne\WinPython\python-3.4.4.amd64\lib\site-packages\scipy\optimize\optimize.py", line 292, in function_wrapper
    return function(*(wrapper_args + args))
  File "C:\Lasagne\WinPython\python-3.4.4.amd64\lib\site-packages\scipy\optimize\optimize.py", line 63, in __call__
    fg = self.fun(x, *args)
  File "doodle.py", line 536, in evaluate
    best_idx = self.evaluate_slices(f, l)
  File "doodle.py", line 504, in evaluate_slices
    layer.W.set_value(weights)
  File "C:\Lasagne\WinPython\python-3.4.4.amd64\lib\site-packages\theano\compile\sharedvalue.py", line 127, in set_value
    self.container.value = copy.deepcopy(new_value)
  File "C:\Lasagne\WinPython\python-3.4.4.amd64\lib\site-packages\theano\gof\link.py", line 479, in __set__
    self.storage[0] = self.type.filter(value, **kwargs)
  File "C:\Lasagne\WinPython\python-3.4.4.amd64\lib\site-packages\theano\tensor\type.py", line 195, in filter
    " dimension.", data.shape, self.broadcastable)
TypeError: ('Non-unit value on shape on a broadcastable dimension.', (472, 256, 3, 3), (True, False, False, False), 'Container name "None"')`

**Comment by ssccsscc** [comment]
Fixed. I installed requirements.txt from neural-enhance instead of neural-doodle.
