### ISSUE TITLE
Hi, TypeError: ('Non-unit size in broadcastable dimension 0', 'Container name "None"')

### ISSUE THREAD

**Issue by huihuangz** [alexjc/neural-doodle#110]
>>>python3 doodle.py --style samples/Renoir.jpg --output samples/Landscape.png --device=gpu0 --iterations=80
Neural Doodle for semantic style transfer.
  - Using device `gpu0` for processing the images.
  - Adding `samples/Landscape_sem.png` as semantic map.
  - Loading `samples/Renoir.jpg` for style data.
  - Adding `samples/Renoir_sem.png` as semantic map.

Phase #0: resolution 128x80  scale 0.25
  - Style layer 3_1: (540, 259, 3, 3) patches in 1,258kb.
  - Style layer 4_1: (112, 515, 3, 3) patches in 519kb.

Traceback (most recent call last):
  File "doodle.py", line 658, in <module>
    generator.run()
  File "doodle.py", line 635, in run
    iprint=-1)                       # Handle our own logging of information.
  File "/home/zhao/.local/lib/python3.4/site-packages/scipy/optimize/lbfgsb.py", line 193, in fmin_l_bfgs_b
    **opts)
  File "/home/zhao/.local/lib/python3.4/site-packages/scipy/optimize/lbfgsb.py", line 328, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/home/zhao/.local/lib/python3.4/site-packages/scipy/optimize/lbfgsb.py", line 278, in func_and_grad
    f = fun(x, *args)
  File "/home/zhao/.local/lib/python3.4/site-packages/scipy/optimize/optimize.py", line 292, in function_wrapper
    return function(*(wrapper_args + args))
  File "/home/zhao/.local/lib/python3.4/site-packages/scipy/optimize/optimize.py", line 63, in __call__
    fg = self.fun(x, *args)
  File "doodle.py", line 536, in evaluate
    best_idx = self.evaluate_slices(f, l)
  File "doodle.py", line 504, in evaluate_slices
    layer.W.set_value(weights)
  File "/usr/local/lib/python3.4/site-packages/theano/sandbox/cuda/var.py", line 154, in set_value
    self.container.value = value  # this will copy a numpy ndarray
  File "/usr/local/lib/python3.4/site-packages/theano/gof/link.py", line 466, in __set__
    **kwargs)
  File "/usr/local/lib/python3.4/site-packages/theano/sandbox/cuda/type.py", line 118, in filter_inplace
    strict, old_data)
TypeError: ('Non-unit size in broadcastable dimension 0', 'Container name "None"')

Specs:  Ubutun 16.4, python 3.4.5, Theano 0.9.0.dev4, Lasagne 0.2.dev1, GTX TIT, Cuda 8 + CudNN
i got the version of Theano and others that are from requirements.txt.

Could you please help me understand a bit more about the errors ?

Many thanks

**Comment by huihuangz** [comment]
For this problem, I've downgraded Lasagne by uninstalling, then installing an older commit, which seems to have fixed the problem:

pip3 uninstall Lasagne
pip3 install git+git://github.com/Lasagne/Lasagne.git@31ac7d2bbcb4777b9a500b

Thanks 
https://github.com/alexjc/neural-doodle/issues/106
