### ISSUE TITLE
unable to run docker image

### ISSUE THREAD

**Issue by hurnhu** [alexjc/neural-doodle#121]
im unable to run the docker image at all it crashes on with this error.
ive seen this issue has been reported but no answers, anything on this?

```
u@Ubuntu-1710-artful-64-minimal:~/github/neural-doodle$ sudo docker run -v $(pwd)/samples:/nd/samples -v $(pwd)/frames:/nd/frames -it alexjc/neural-doodle
Neural Doodle for semantic style transfer.
  - Using device `cpu` for processing the images.
Traceback (most recent call last):
  File "doodle.py", line 657, in <module>
    generator = NeuralGenerator()
  File "doodle.py", line 234, in __init__
    self.style_img_original, self.style_map_original = self.load_images('style', args.style)
  File "doodle.py", line 288, in load_images
    basename, _ = os.path.splitext(filename)
  File "/usr/lib/python3.4/posixpath.py", line 122, in splitext
    return genericpath._splitext(p, sep, None, extsep)
  File "/usr/lib/python3.4/genericpath.py", line 118, in _splitext
    sepIndex = p.rfind(sep)
AttributeError: 'NoneType' object has no attribute 'rfind'

```

**Comment by ProGamerGov** [comment]
https://github.com/alexjc/neural-doodle/issues/104

https://github.com/alexjc/neural-doodle/issues/103

Looks like it's a Python issue. 

https://github.com/berdario/pew/issues/63

https://github.com/pyinstaller/pyinstaller/issues/1839

https://github.com/openai/universe/issues/72

https://stackoverflow.com/questions/37716326/python-attributeerror-nonetype-object-has-no-attribute-rfind

https://github.com/dugsong/pypcap/issues/49

https://github.com/pynetwork/pypcap/issues/33

https://community.plone.org/t/cant-save-pfg-mailer-adapter-compilation-failed-exceptions-attributeerror-nonetype-object-has-no-attribute-rfind/5088/6

**Comment by ProGamerGov** [comment]
Your error lists: 

https://github.com/alexjc/neural-doodle/blob/master/doodle.py#L657

https://github.com/alexjc/neural-doodle/blob/master/doodle.py#L234

**Comment by ProGamerGov** [comment]
@alexjc Are you able to help fix the issue?

**Comment by ProGamerGov** [comment]
I installed it manually as per: 

> Linux Installation of Lasagne (intermediate)

And it works: 

`python3 doodle.py --style samples/Seth.jpg --content samples/Gogh.png --output GoghAsSeth.png --device=cuda --phases=4 --iterations=80 2>&1 | tee ~/neural-doodle/mylog.log`

```
ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.7 or higher required)
NoneType
/home/ubuntu/.local/lib/python3.5/site-packages/lasagne/layers/pool.py:266: UserWarning: DEPRECATION: the 'ds' parameter is not going to exist anymore as it is going to be replaced by the parameter 'ws'.
  mode=self.mode,
/home/ubuntu/.local/lib/python3.5/site-packages/lasagne/layers/pool.py:266: UserWarning: DEPRECATION: the 'st' parameter is not going to exist anymore as it is going to be replaced by the parameter 'stride'.
  mode=self.mode,
/home/ubuntu/.local/lib/python3.5/site-packages/lasagne/layers/pool.py:266: UserWarning: DEPRECATION: the 'padding' parameter is not going to exist anymore as it is going to be replaced by the parameter 'pad'.
  mode=self.mode,
/home/ubuntu/.local/lib/python3.5/site-packages/lasagne/layers/pool.py:266: UserWarning: DEPRECATION: the 'ds' parameter is not going to exist anymore as it is going to be replaced by the parameter 'ws'.
  mode=self.mode,
/home/ubuntu/.local/lib/python3.5/site-packages/lasagne/layers/pool.py:266: UserWarning: DEPRECATION: the 'st' parameter is not going to exist anymore as it is going to be replaced by the parameter 'stride'.
  mode=self.mode,
/home/ubuntu/.local/lib/python3.5/site-packages/lasagne/layers/pool.py:266: UserWarning: DEPRECATION: the 'padding' parameter is not going to exist anymore as it is going to be replaced by the parameter 'pad'.
  mode=self.mode,
WARNING (theano.tensor.blas): We did not find a dynamic library in the library_dir of the library we use for blas. If you use ATLAS, make sure to compile it with dynamics library.
[1;36mNeural Doodle for semantic style transfer.[0m
[0;36m  - Using device `cuda` for processing the images.[0m
[0;36m  - Adding `samples/Gogh_sem.png` as semantic map.
  - Loading `samples/Seth.jpg` for style data.
  - Adding `samples/Seth_sem.png` as semantic map.
[0m
[1;94mPhase #0: resolution 52x63  scale 0.125[0;94m
  - Style layer 3_1: (126, 259, 3, 3) patches in 293kb.
  - Style layer 4_1: (18, 515, 3, 3) patches in 83kb.
[0m
  0   [1;97mloss[0m 6.68e+03   [1;97mstyle[0m [1;97m3_1[0m 9.89e+02  [1;97m4_1[0m 5.48e+03   [1;97mquality[0m  2.3%   [1;97mtime[0m 0.2s 
 10   [1;97mloss[0m 2.06e+03   [1;97mstyle[0m [1;97m3_1[0m 5.50e+02  [1;97m4_1[0m 1.39e+03   [1;97mquality[0m 27.6%   [1;97mtime[0m 1.6s 
 20   [1;97mloss[0m 1.57e+03   [1;97mstyle[0m [1;97m3_1[0m 4.33e+02  [1;97m4_1[0m 1.06e+03   [1;97mquality[0m 45.7%   [1;97mtime[0m 1.6s 
 30   [1;97mloss[0m 1.38e+03   [1;97mstyle[0m [1;97m3_1[0m 3.64e+02  [1;97m4_1[0m 9.70e+02   [1;97mquality[0m 58.2%   [1;97mtime[0m 3.5s 
 40   [1;97mloss[0m 1.27e+03   [1;97mstyle[0m [1;97m3_1[0m 3.08e+02  [1;97m4_1[0m 9.35e+02   [1;97mquality[0m 66.9%   [1;97mtime[0m 1.7s 
 50   [1;97mloss[0m 1.22e+03   [1;97mstyle[0m [1;97m3_1[0m 2.80e+02  [1;97m4_1[0m 9.18e+02   [1;97mquality[0m 70.7%   [1;97mtime[0m 1.7s 
 60   [1;97mloss[0m 1.18e+03   [1;97mstyle[0m [1;97m3_1[0m 2.62e+02  [1;97m4_1[0m 9.09e+02   [1;97mquality[0m 73.1%   [1;97mtime[0m 1.7s 
 70   [1;97mloss[0m 1.16e+03   [1;97mstyle[0m [1;97m3_1[0m 2.48e+02  [1;97m4_1[0m 9.01e+02   [1;97mquality[0m 75.0%   [1;97mtime[0m 1.7s 

[1;94mPhase #1: resolution 104x127  scale 0.25[0;94m
  - Style layer 3_1: (600, 259, 3, 3) patches in 1,398kb.
  - Style layer 4_1: (126, 515, 3, 3) patches in 584kb.
[0m
 80   [1;97mloss[0m 2.47e+03   [1;97mstyle[0m [1;97m3_1[0m 5.27e+02  [1;97m4_1[0m 1.94e+03   [1;97mquality[0m  3.8%   [1;97mtime[0m 0.7s 
 90   [1;97mloss[0m 1.02e+03   [1;97mstyle[0m [1;97m3_1[0m 2.60e+02  [1;97m4_1[0m 7.59e+02   [1;97mquality[0m 36.6%   [1;97mtime[0m 6.0s 
100   [1;97mloss[0m 8.60e+02   [1;97mstyle[0m [1;97m3_1[0m 2.08e+02  [1;97m4_1[0m 6.50e+02   [1;97mquality[0m 56.2%   [1;97mtime[0m 5.9s 

```

**Comment by ProGamerGov** [comment]
Neural-Doodle doesn't link to a guide for using GPUs, I think? 

https://dwijaybane.wordpress.com/2017/07/23/setup-theano-with-cuda-support-on-ubuntu-16-04/
