### ISSUE TITLE
Error when testing custom images

### ISSUE THREAD

**Issue by ProGamerGov** [alexjc/neural-doodle#122]
```
Traceback (most recent call last):
  File "doodle.py", line 658, in <module>
    generator.run()
  File "doodle.py", line 635, in run
    iprint=-1)                       # Handle our own logging of information.
  File "/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/lbfgsb.py", line 199, in fmin_l_bfgs_b
    **opts)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/lbfgsb.py", line 335, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/lbfgsb.py", line 285, in func_and_grad
    f = fun(x, *args)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 292, in function_wrapper
    return function(*(wrapper_args + args))
  File "/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 63, in __call__
    fg = self.fun(x, *args)
  File "doodle.py", line 536, in evaluate
    best_idx = self.evaluate_slices(f, l)
  File "doodle.py", line 504, in evaluate_slices
    layer.W.set_value(weights)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/theano/gpuarray/type.py", line 638, in set_value
    self.container.value = value
  File "/home/ubuntu/.local/lib/python3.5/site-packages/theano/gof/link.py", line 477, in __set__
    **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/theano/gpuarray/type.py", line 293, in filter_inplace
    " dimension.", shp, self.broadcastable)
TypeError: ('Non-unit value on shape on a broadcastable dimension.', (345, 260, 3, 3), (True, False, False, False), 'Container name "None"')
```

**Comment by ProGamerGov** [comment]
I fixed the issue by uninstalling a duplicate version of lasagna.
