### ISSUE TITLE
ValueError: unknown locale: UTF-8

### ISSUE THREAD

**Issue by holyxiaoxin** [alexjc/neural-doodle#13]
Tried to run `python3 doodle.py --style samples/Monet.jpg --output samples/Coastline.png --device=cpu --iterations=40` after installation but got the following errors:

```
Traceback (most recent call last):
  File "doodle.py", line 69, in <module>
    import skimage.transform
  File "/usr/local/lib/python3.5/site-packages/skimage/transform/__init__.py", line 1, in <module>
    from .hough_transform import (hough_line, hough_line_peaks,
  File "/usr/local/lib/python3.5/site-packages/skimage/transform/hough_transform.py", line 4, in <module>
    from ._hough_transform import (_hough_circle,
  File "skimage/transform/_hough_transform.pyx", line 13, in init skimage.transform._hough_transform (skimage/transform/_hough_transform.c:23691)
  File "/usr/local/lib/python3.5/site-packages/skimage/draw/__init__.py", line 1, in <module>
    from .draw import circle, ellipse, polygon_perimeter, set_color
  File "/usr/local/lib/python3.5/site-packages/skimage/draw/draw.py", line 6, in <module>
    from .._shared._geometry import polygon_clip
  File "/usr/local/lib/python3.5/site-packages/skimage/_shared/_geometry.py", line 4, in <module>
    from matplotlib import _path, path, transforms
  File "/usr/local/lib/python3.5/site-packages/matplotlib/__init__.py", line 1131, in <module>
    rcParams = rc_params()
  File "/usr/local/lib/python3.5/site-packages/matplotlib/__init__.py", line 975, in rc_params
    return rc_params_from_file(fname, fail_on_error)
  File "/usr/local/lib/python3.5/site-packages/matplotlib/__init__.py", line 1100, in rc_params_from_file
    config_from_file = _rc_params_in_file(fname, fail_on_error)
  File "/usr/local/lib/python3.5/site-packages/matplotlib/__init__.py", line 1018, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/site-packages/matplotlib/__init__.py", line 1000, in _open_file_or_url
    encoding = locale.getdefaultlocale()[1]
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/locale.py", line 559, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/locale.py", line 487, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
```

**Comment by alexjc** [comment]
Try `export LC_ALL=en_US.UTF-8`. I think your machine is misconfigured?

**Comment by holyxiaoxin** [comment]
It's all well now. Thanks. (:
