### ISSUE TITLE
TypeError: ('Non-unit value on shape on a broadcastable dimension.', (71, 259, 3, 3), (True, False, False, False), 'Container name "None"')

### ISSUE THREAD

**Issue by longyunyun** [alexjc/neural-doodle#131]
Dear friends,

I have such an error while run the doodle script (for every examples):
for example

python3 doodle.py --style samples/Monet.jpg --output samples/Coastline.png --device=cpu --iterations=40

D:\ProgramData\Anaconda3\envs\neural-doodle\python.exe E:/MyRead/neural-doodle/doodle.py
Neural Doodle for semantic style transfer.
  - Using device `cpu` for processing the images.
  - Adding `samples/Seth_sem.png` as semantic map.
  - Loading `samples/Gogh.jpg` for style data.
  - Adding `samples/Gogh_sem.png` as semantic map.

Phase #0: resolution 44x64  scale 0.125
  - Style layer 3_1: (143, 259, 3, 3) patches in 333kb.
  - Style layer 4_1: (20, 515, 3, 3) patches in 92kb.

Traceback (most recent call last):
  File "E:/MyRead/neural-doodle/doodle.py", line 659, in <module>
    generator.run()
  File "E:/MyRead/neural-doodle/doodle.py", line 636, in run
    iprint=-1)                       # Handle our own logging of information.
  File "D:\ProgramData\Anaconda3\envs\neural-doodle\lib\site-packages\scipy\optimize\lbfgsb.py", line 199, in fmin_l_bfgs_b
    **opts)
  File "D:\ProgramData\Anaconda3\envs\neural-doodle\lib\site-packages\scipy\optimize\lbfgsb.py", line 335, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "D:\ProgramData\Anaconda3\envs\neural-doodle\lib\site-packages\scipy\optimize\lbfgsb.py", line 285, in func_and_grad
    f = fun(x, *args)
  File "D:\ProgramData\Anaconda3\envs\neural-doodle\lib\site-packages\scipy\optimize\optimize.py", line 300, in function_wrapper
    return function(*(wrapper_args + args))
  File "D:\ProgramData\Anaconda3\envs\neural-doodle\lib\site-packages\scipy\optimize\optimize.py", line 63, in __call__
    fg = self.fun(x, *args)
  File "E:/MyRead/neural-doodle/doodle.py", line 537, in evaluate
    best_idx = self.evaluate_slices(f, l)
  File "E:/MyRead/neural-doodle/doodle.py", line 505, in evaluate_slices
    layer.W.set_value(weights)
  File "D:\ProgramData\Anaconda3\envs\neural-doodle\lib\site-packages\theano\compile\sharedvalue.py", line 148, in set_value
    self.container.value = copy.deepcopy(new_value)
  File "D:\ProgramData\Anaconda3\envs\neural-doodle\lib\site-packages\theano\gof\link.py", line 479, in __set__
    self.storage[0] = self.type.filter(value, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\neural-doodle\lib\site-packages\theano\tensor\type.py", line 195, in filter
    " dimension.", data.shape, self.broadcastable)
TypeError: ('Non-unit value on shape on a broadcastable dimension.', (71, 259, 3, 3), (True, False, False, False), 'Container name "None"')

**Comment by Saycka** [comment]
I have the same problem. I used this instruction to install https://github.com/Lasagne/Lasagne/wiki/From-Zero-to-Lasagne-on-Windows-7-%2864-bit%29
