### ISSUE TITLE
OSError: Invalid data stream on OSX El capitan

### ISSUE THREAD

**Issue by garnett** [alexjc/neural-doodle#18]
```
python3 doodle.py --style samples/Monet.jpg --output samples/Coastline.png \
                  --device=cpu --iterations=40
Neural Doodle for semantic style transfer.
  - Using device `cpu` for processing the images.
Traceback (most recent call last):
  File "doodle.py", line 487, in <module>
    generator = NeuralGenerator()
  File "doodle.py", line 195, in __init__
    self.model = Model()
  File "doodle.py", line 99, in __init__
    self.load_data()
  File "doodle.py", line 151, in load_data
    data = pickle.load(bz2.open('vgg19_conv.pkl.bz2', 'rb'))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/bz2.py", line 171, in peek
    return self._buffer.peek(n)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/_compression.py", line 103, in read
    data = self._decompressor.decompress(rawblock, size)
OSError: Invalid data stream
```

**Comment by garnett** [comment]
curl failed to load samples correctly. Redownloading manually helped

**Comment by Hey-tom** [comment]
Hi Garnett, I've the same error decompressing data. Can you let me know if you encountered this issue decompressing bz2 files?
