### ISSUE TITLE
How to run it faster without NVIDIA gpu

### ISSUE THREAD

**Issue by alephman** [alexjc/neural-doodle#46]
My laptop doesn't have NVIDIA GPU,  it seems all machine learning packages depend on CUDA. Is there a way to use Intel or AMD gpu in those algorithms?

**Comment by alexjc** [comment]
This code depends on Theano, so if there's an OpenCL version that works you may be able to use that. I haven't tried it though.

**Comment by FrankiePo** [comment]
Actually, theano has beta OpenCL support. It might be enough for the task.

**Comment by alexjc** [comment]
Let me know!

**Comment by rayset** [comment]
opencl user reporting in. amd radeon 280x, 3gb of vram.

the program is running, this is the output it gave me running a test. does it look as it should? 100 iterations per phase (I guess, I used the default).

![landscape](https://cloud.githubusercontent.com/assets/9410263/13865449/eadea2c8-ecab-11e5-8dc9-57377fbb8c57.png)


I'm not 100% sure it used the gpu, even if I heard the fans it took quite a lot of time.

it took 10 minutes to end phase 1 and another 50 minutes (sounds too long for being on gpu, but I heard opencl is up to 10 times slower than cuda) for phase 3. I have a 4770 i7 and 8gbs of ram.

this is the traceback I got, opencl0:0 should be the name of my gpu that theano uses.

`python3 doodle.py --style samples/Renoir.jpg --output samples/Landscape.png                   --device=opencl0:0
Neural Doodle for semantic style transfer.
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.4/logging/__init__.py", line 978, in emit
    msg = self.format(record)
  File "/usr/lib/python3.4/logging/__init__.py", line 828, in format
    return fmt.format(record)
  File "/usr/lib/python3.4/logging/__init__.py", line 573, in format
    record.exc_text = self.formatException(record.exc_info)
  File "/usr/lib/python3.4/logging/__init__.py", line 523, in formatException
    traceback.print_exception(ei[0], ei[1], tb, None, sio)
  File "/usr/lib/python3.4/traceback.py", line 169, in print_exception
    for line in _format_exception_iter(etype, value, tb, limit, chain):
  File "/usr/lib/python3.4/traceback.py", line 146, in _format_exception_iter
    for value, tb in values:
  File "/usr/lib/python3.4/traceback.py", line 125, in _iter_chain
    context = exc.__context__
AttributeError: 'NoneType' object has no attribute '__context__'
Call stack:
  File "doodle.py", line 72, in <module>
    import theano
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/deep/neural-doodle/pyvenv/lib/python3.4/site-packages/theano/__init__.py", line 118, in <module>
    import theano.sandbox.gpuarray
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/deep/neural-doodle/pyvenv/lib/python3.4/site-packages/theano/sandbox/gpuarray/__init__.py", line 131, in <module>
    error("pygpu was configured but could not be imported", exc_info=True)
Message: 'pygpu was configured but could not be imported'
Arguments: ()
  - Using device `opencl0:0` for processing the images.
  - Loading content semantic map from samples/Landscape_sem.png.
  - Loading style image data from samples/Renoir.jpg.
  - Loading style semantic map from samples/Renoir_sem.png.

Phase #0: resolution 128x80  scale 0.25
  - Style layer sem3_1: 540 patches in 1,258kb.
  - Style layer sem4_1: 112 patches in 519kb.

  0   error 7.64e+03   style 3_1 1.08e+03  4_1 6.42e+03   quality 3.6% 
 10   error 3.93e+03   style 3_1 7.91e+02  4_1 3.04e+03   quality 37.0% 
 20   error 3.46e+03   style 3_1 7.06e+02  4_1 2.67e+03   quality 56.5% 
 30   error 3.27e+03   style 3_1 6.62e+02  4_1 2.55e+03   quality 68.4% 
 40   error 3.17e+03   style 3_1 6.31e+02  4_1 2.49e+03   quality 73.5% 
 50   error 3.11e+03   style 3_1 6.15e+02  4_1 2.46e+03   quality 75.6% 
 60   error 3.07e+03   style 3_1 6.00e+02  4_1 2.44e+03   quality 74.8% 
 70   error 3.04e+03   style 3_1 5.90e+02  4_1 2.42e+03   quality 77.1% 
 80   error 3.02e+03   style 3_1 5.84e+02  4_1 2.41e+03   quality 77.1% 
 90   error 3.00e+03   style 3_1 5.78e+02  4_1 2.41e+03   quality 77.1% 

Phase #1: resolution 256x160  scale 0.5
  - Style layer sem3_1: 2356 patches in 5,491kb.
  - Style layer sem4_1: 540 patches in 2,502kb.

100   error 4.29e+03   style 3_1 7.72e+02  4_1 3.52e+03   quality 4.6% 
110   error 2.30e+03   style 3_1 4.23e+02  4_1 1.88e+03   quality 40.6% 
120   error 2.17e+03   style 3_1 3.93e+02  4_1 1.78e+03   quality 61.8% 
130   error 2.12e+03   style 3_1 3.78e+02  4_1 1.74e+03   quality 73.0% 
140   error 2.09e+03   style 3_1 3.68e+02  4_1 1.72e+03   quality 79.6% 
150   error 2.07e+03   style 3_1 3.61e+02  4_1 1.71e+03   quality 80.9% 
160   error 2.06e+03   style 3_1 3.55e+02  4_1 1.70e+03   quality 82.3% 
170   error 2.04e+03   style 3_1 3.51e+02  4_1 1.69e+03   quality 84.3% 
180   error 2.03e+03   style 3_1 3.47e+02  4_1 1.68e+03   quality 84.5% 
190   error 2.02e+03   style 3_1 3.44e+02  4_1 1.68e+03   quality 85.3% 

Phase #2: resolution 512x320  scale 1.0
  - Style layer sem3_1: 9828 patches in 22,909kb.
  - Style layer sem4_1: 2356 patches in 10,920kb.

200   error 2.92e+03   style 3_1 4.56e+02  4_1 2.46e+03   quality 5.0% 
210   error 1.57e+03   style 3_1 2.96e+02  4_1 1.27e+03   quality 42.7% 
220   error 1.45e+03   style 3_1 2.73e+02  4_1 1.17e+03   quality 65.0% 
230   error 1.40e+03   style 3_1 2.63e+02  4_1 1.13e+03   quality 77.3% 
240   error 1.36e+03   style 3_1 2.54e+02  4_1 1.11e+03   quality 84.5% 
250   error 1.34e+03   style 3_1 2.47e+02  4_1 1.09e+03   quality 88.5% 
260   error 1.32e+03   style 3_1 2.42e+02  4_1 1.08e+03   quality 90.3% 
270   error 1.30e+03   style 3_1 2.36e+02  4_1 1.07e+03   quality 91.5% 
280   error 1.29e+03   style 3_1 2.33e+02  4_1 1.06e+03   quality 92.5% 
290   error 1.28e+03   style 3_1 2.29e+02  4_1 1.05e+03   quality 92.8% 

`

what do you think? is it running in cpu? I don't have anything related to cuda installed, and my theano works on gpu by default. it tried reinstalling it tho (I guess is because mine is on python 2 and another virtual eviroment? I don't know much about this stuff I installed it for this https://github.com/awentzonline/image-analogies following theano's wiki and using python 2 since I heard it woudn't run on 3 (or maybe it woudn't run on gpu...I don't know tbh) )

htop is a bit strange, it gives me odd informations.

![schermata del 2016-03-18 01-11-06](https://cloud.githubusercontent.com/assets/9410263/13864961/705cd632-eca6-11e5-913f-a9d662b45db3.png) every  minute or so it goes like this, but then returns to this:
![schermata del 2016-03-18 01-11-18](https://cloud.githubusercontent.com/assets/9410263/13864982/ad549782-eca6-11e5-89d8-d71434ff33d7.png)
is this some kind of ''starting a new iteration, calculating,and starting again? it stays for very few seconds at 100%, like 1 or 2, so I'm not so sure about it. once in a while core 2 stucks at 100% tho.
I don't know why it says it has been running for more than 1h, that picture was taken when it was running for about 30 minutes.

if I can help in any way let me know, I really want to see it running on opencl in a perfect way!

**Comment by rayset** [comment]
just a follow up.

running on cpu mode the whole error log at the begin is absent. I guess this is a good sign? it seems to be a bit slower (at least in phase 0) but I don't see the difference I was especting. I'm almost sure it runs in both cases on cpu,

the fact that it names ''gpuarray'' in the error log is a good sign imho, it's at least trying to run on opengl. then we get that error about pygpu, which seems to be related to using python3 instad of python2 (reading issues on pygpu).
I hope we are close to a solution, this software is awesome.

**Comment by FrankiePo** [comment]
@rayset good job!
Probably, code below helps you to confirm gpu use. It was given in [Theano documentation](http://deeplearning.net/software/theano/tutorial/using_gpu.html).
You can try it to ensure.
```
from theano import function, config, shared, tensor, sandbox
import numpy
import time

vlen = 10 * 30 * 768  # 10 x #cores x # threads per core
iters = 1000

rng = numpy.random.RandomState(22)
x = shared(numpy.asarray(rng.rand(vlen), config.floatX))
f = function([], tensor.exp(x))
print(f.maker.fgraph.toposort())
t0 = time.time()
for i in range(iters):
    r = f()
t1 = time.time()
print("Looping %d times took %f seconds" % (iters, t1 - t0))
print("Result is %s" % (r,))
if numpy.any([isinstance(x.op, tensor.Elemwise) and
              ('Gpu' not in type(x.op).__name__)
              for x in f.maker.fgraph.toposort()]):
    print('Used the cpu')
else:
    print('Used the gpu')
```
Btw, what have you done to be able to run theano with opencl?

**Comment by rayset** [comment]
yup, with that testing it runs on gpu.

It may be that I have 2 theano installed tho, the script to install neural doodle dowloaded theano (even if it was already installed and configured), I'm not sure neural doodle calls the theano I want.
The fact that I have to pass the flag --device=opencl0:0 is strange, I have the default device for theano (in the config file) set as opencl0:0...so uhm, it could be. I had to reinstall numpy and scipy too.

To make it work with opencl I used this: http://deeplearning.net/software/theano/tutorial/using_gpu.html (the part with gpu array), it was quite hard installing gpuarray (path problems) but the developer helped me on github.

In the error log above it names ''gpuarray'' with is the component to run opencl. then it fails loading pygpu. The more I think about it the more I suspect it's using a second theano it downloaded and installed instead of the one I already had.

**Comment by FrankiePo** [comment]
I'm not sure, but if you have 2 theano, you might have 1 in your system and 1 in the virtual environment. So if you remove one from the venv, script will use the system theano then.
Am I wrong?

**Comment by rayset** [comment]
I'm sorry but I have no idea of what this virtual enviroment are and how they work.

I made the virtual env from te installation tutorial (pyvenv?) AND this one https://github.com/awentzonline/image-analogies (venv?)

how can I check if my theano is on system/ venv? I could even have installed the first gpu working on the venv enviroment :( 
also if you know how to uninstall it from the virtual envs so that it will run the system one it would be great.

**Comment by TPXP** [comment]
Not a CUDA/OpenCL expert here, but I think there is a very easy way to know if it's your gpu that handles the task : try to move your mouse. As the display runs on the GPU, it should lag a little bit, whereas if running on the cpu it should be OK... At least that is what I noticed while I was mining Bitcoins, so you might get the same results. 

Hope this helps. Great job by the way!

**Comment by alexjc** [comment]
@rayset I added more detailed instructions on the front page for installing on Windows and Linux.

**Comment by rayset** [comment]
in the end does it work with opencl? I sold my gpu waiting for 1070/480 to be in stock

**Comment by alexjc** [comment]
From what I found out, Theano's OpenCL backend currently does not support convolution. So it would basically use the CPU fallback.

**Comment by ddofer** [comment]
Anyone using openCL: How did you set it up in the first place with Theano?

**Comment by alexjc** [comment]
@ddofer Theano has instructions for using their new backend, that's what you need. Best install from GitHub directly, and then specify `--device=opencl0:0` on command-line. However, it doesn't work because convolution isn't supported.
