### ISSUE TITLE
Issue running on GPU

### ISSUE THREAD

**Issue by dxmachina** [alexjc/neural-doodle#49]
Using a 980ti in Ubuntu 14. Running on the CPU is up and running, but can't seem to get the GPU-bound version to function. I'm getting this:

Traceback (most recent call last):
  File "doodle.py", line 72, in <module>
    import theano
  File "/home/sebastiankatz/neural-doodle-master/pyvenv/lib/python3.4/site-packages/theano/__init__.py", line 103, in <module>
    import theano.sandbox.cuda
  File "/home/sebastiankatz/neural-doodle-master/pyvenv/lib/python3.4/site-packages/theano/sandbox/cuda/__init__.py", line 694, in <module>
    use(device=config.device, force=config.force_device, test_driver=False)
  File "/home/sebastiankatz/neural-doodle-master/pyvenv/lib/python3.4/site-packages/theano/sandbox/cuda/__init__.py", line 489, in use
    "" % device)
OSError: You forced the use of gpu device 'gpu0', but nvcc was not found. Set it in your PATH environment variable or set the Theano flags 'cuda.root' to its directory

Any ideas what I can do?

**Comment by dxmachina** [comment]
Sorry - reinstall of CUDA seemed to fix this.

**Comment by alexjc** [comment]
Ah, glad to hear you fixed it!
