### ISSUE TITLE
Exception on samples (unexpected keyword argument 'mode')

### ISSUE THREAD

**Issue by f0086** [alexjc/neural-doodle#6]
```
(pyvenv) $ /tmp/neural-doodle % python3.5 doodle.py --style samples/Monet.jpg --output samples/Coastline.png --device=cpu --iterations=40
Neural Doodle for semantic style transfer.
  - Loading content semantic map from samples/Coastline_sem.png.
  - Loading style image data from samples/Monet.jpg.
  - Loading style semantic map from samples/Monet_sem.png.

Phase #0: resolution 128x96  scale 0.25
Traceback (most recent call last):
  File "doodle.py", line 450, in <module>
    generator.run()
  File "doodle.py", line 408, in run
    self.model.setup(layers=['sem'+l for l in self.style_layers] + ['conv'+l for l in self.style_layers])
  File "doodle.py", line 153, in setup
    outputs = lasagne.layers.get_output([self.network[l] for l in layers], self.tensor_inputs)
  File "/usr/lib/python3.5/site-packages/lasagne/layers/helper.py", line 185, in get_output
    all_outputs[layer] = layer.get_output_for(layer_inputs, **kwargs)
  File "/usr/lib/python3.5/site-packages/lasagne/layers/pool.py", line 240, in get_output_for
    mode=self.mode,
TypeError: max_pool_2d() got an unexpected keyword argument 'mode'
```

Running on ArchLinux

**Comment by alexjc** [comment]
You need to install Lasagne from the `requirements.txt` and not PIP. It requires a development version, the latest package is not enough.
