### ISSUE TITLE
Reproducible crash

### ISSUE THREAD

**Issue by ikarth** [alexjc/neural-doodle#74]
So, trying to use a style image that is smaller than the content image, I get this:

    Error when tring to find the memory information on the GPU: unknown error
    Error freeing device pointer 0000000B02588E00 (unknown error). Driver report 0 bytes free 
    and 0 bytes total
    device_free: cudaFree() returned an error, but there is already an Python error set. This happen
    during the clean up when there is a first error and the CUDA driver is in a so bad state that it 
    don't work anymore. We keep the previous error set to help debugging it.CudaNdarray_uninit: 
    error freeing self->devdata. (self=00000000322BFAB0, self->devata=0000000B02588E00)
    Traceback (most recent call last):
      File "F:\Isaac\Dev\WinPython\python-3.4.4.amd64\lib\site-packages\theano\compile\function_module.py", line 859, in __call__
        outputs = self.fn()
    RuntimeError: Cuda error 'unknown error' while copying 4 data element to device memory. 
    str ptr=0x0000000017986B00. dst ptr=0x0000000B02588E00

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "doodle.py", line 542, in <module>
        generator.run()
      File "doodle.py", line 527, in run
        iprint=-1)                       # Handle our own logging of information.
      File "F:\Isaac\Dev\WinPython\python-3.4.4.amd64\lib\site-packages\scipy\optimize\lbfgsb.py", line 193, in fmi
    n_l_bfgs_b
        **opts)
      File "F:\Isaac\Dev\WinPython\python-3.4.4.amd64\lib\site-packages\scipy\optimize\lbfgsb.py", line 330, in _mi
    nimize_lbfgsb
        f, g = func_and_grad(x)
      File "F:\Isaac\Dev\WinPython\python-3.4.4.amd64\lib\site-packages\scipy\optimize\lbfgsb.py", line 278, in fun
    c_and_grad
        f = fun(x, *args)
      File "F:\Isaac\Dev\WinPython\python-3.4.4.amd64\lib\site-packages\scipy\optimize\optimize.py", line 289, in f
    unction_wrapper
        return function(*(wrapper_args + args))
      File "F:\Isaac\Dev\WinPython\python-3.4.4.amd64\lib\site-packages\scipy\optimize\optimize.py", line 63, in __
    call__
        fg = self.fun(x, *args)
      File "doodle.py", line 442, in evaluate
        grads, *losses = self.compute_grad_and_losses(current_img, self.content_map)
      File "F:\Isaac\Dev\WinPython\python-3.4.4.amd64\lib\site-packages\theano\compile\function_module.py", line 87
    1, in __call__
        storage_map=getattr(self.fn, 'storage_map', None))
      File "F:\Isaac\Dev\WinPython\python-3.4.4.amd64\lib\site-packages\theano\gof\link.py", line 314, in raise_wit
    h_op
        reraise(exc_type, exc_value, exc_trace)
      File "F:\Isaac\Dev\WinPython\python-3.4.4.amd64\lib\site-packages\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "F:\Isaac\Dev\WinPython\python-3.4.4.amd64\lib\site-packages\theano\compile\function_module.py", line 85
    9, in __call__
        outputs = self.fn()
    RuntimeError: Cuda error 'unknown error' while copying 4 data element to device memory. str ptr=0x0000000011A37
    910. dst ptr=0x0000000B02588E00
    Apply node that caused the error: GpuFromHost(Elemwise{Cast{float32}}.0)
    Toposort index: 333
    Inputs types: [TensorType(float32, vector)]
    Inputs shapes: [(4,)]
    Inputs strides: [(4,)]
    Inputs values: [array([  2.11680000e+04,   2.56000000e+02,   3.00000000e+00,
             3.00000000e+00], dtype=float32)]
    Outputs clients: [[GpuSubtensor{int64}(GpuFromHost.0, Constant{3}), GpuSubtensor{int64}(GpuFromHost.0, Constant
    {0}), GpuSubtensor{int64}(GpuFromHost.0, Constant{1}), GpuSubtensor{int64}(GpuFromHost.0, Constant{2})]]

    HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
  HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

Followed by the graphics driver and Python crashing, which is entertaining.

I don't know yet what exactly caused the crash. Using a bigger style image and smaller content image doesn't crash. Using a different smaller style image with the same larger content image does.

This is on Window 7, with WinPython.

![woods](https://cloud.githubusercontent.com/assets/1009991/14401441/5517dac4-fde1-11e5-93b7-1148503733a1.png)
woods.png
![woods_sem](https://cloud.githubusercontent.com/assets/1009991/14401452/9aa91be8-fde1-11e5-9f6c-9f9ed602e4fd.png)
woods_sem.png

![woods_style5_256](https://cloud.githubusercontent.com/assets/1009991/14401449/871bb5e0-fde1-11e5-8c6f-bc464f2bb5a4.png)
woods_style5_256.png
![woods_style5_256_sem](https://cloud.githubusercontent.com/assets/1009991/14401451/8f6016ec-fde1-11e5-8556-f6d827558f79.png)
woods_style5_256_sem.png

    python doodle.py --style art/woods_style5_256.png --content art/woods.png --output art/woods_big_test.png --device=gpu0 --resolutions=3 --iterations=10 --seed=content

**Comment by ikarth** [comment]
It's not just related to the size: I can process a different larger image (with different, larger dimensions) and just get an out of memory error, as expected. Doing it with a different image with the same dimentions gets a crash.

**Comment by alexjc** [comment]
If you use a size that's a multiple of 16 does it help? If someone can try this on Linux or OSX I'd appreciate it!

**Comment by ikarth** [comment]
The larger image is 512x683, the smaller image is 256x256. Testing with a 512x512 larger image doesn't crash...but that might be because it doesn't go over the memory limit.

This is on a GeForce GTX 960 with 2GB, by the way.

**Comment by alexjc** [comment]
This is likely a bug with Theano, though I'm not sure yet if it's Windows specific. If it's on Linux too (a more commonly supported platform) we can escalate it.
