### ISSUE TITLE
can use my own paintings

### ISSUE THREAD

**Issue by Hallr841** [alexjc/neural-doodle#76]
I have been trying to use  my own painting images with out using annotations but other images I keep. will it not take two photos
  

python3 doodle.py --style samples/fireplace.jpg --content samples/orange.png \
> --output fireplaceAsorange.png --device=cpu --phase=4 --iterations=40
Neural Doodle for semantic style transfer.
  - Using device `cpu` for processing the images.
  - Loading content image data from samples/orange.png.
  - Loading style image data from samples/fireplace.jpg.

Phase #0: resolution 21x21  scale 0.125
  - Style layer 3_1: 504 patches in 1,161kb.
  - Style layer 4_1: 104 patches in 479kb.
  - Semantic layer 3_1: 504 patches in 4kb.
  - Semantic layer 4_1: 104 patches in 0kb.
  - Content layer conv4_2: 512 features in 2kb.

Traceback (most recent call last):
  File "/Users/Ryan/pyvenv/lib/python3.4/site-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
TypeError: neib_shape[0]=3, neib_step[0]=1 and ten4.shape[2]=2 not consistent

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "doodle.py", line 555, in <module>
    generator.run()
  File "doodle.py", line 538, in run
    iprint=-1)                       # Handle our own logging of information.
  File "/Users/Ryan/pyvenv/lib/python3.4/site-packages/scipy/optimize/lbfgsb.py", line 193, in fmin_l_bfgs_b
    **opts)
  File "/Users/Ryan/pyvenv/lib/python3.4/site-packages/scipy/optimize/lbfgsb.py", line 330, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/Users/Ryan/pyvenv/lib/python3.4/site-packages/scipy/optimize/lbfgsb.py", line 278, in func_and_grad
    f = fun(x, *args)
  File "/Users/Ryan/pyvenv/lib/python3.4/site-packages/scipy/optimize/optimize.py", line 289, in function_wrapper
    return function(*(wrapper_args + args))
  File "/Users/Ryan/pyvenv/lib/python3.4/site-packages/scipy/optimize/optimize.py", line 63, in __call__
    fg = self.fun(x, *args)
  File "doodle.py", line 447, in evaluate
    grads, *losses = self.compute_grad_and_losses(current_img, self.content_map)
  File "/Users/Ryan/pyvenv/lib/python3.4/site-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/Users/Ryan/pyvenv/lib/python3.4/site-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/Users/Ryan/pyvenv/lib/python3.4/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/Ryan/pyvenv/lib/python3.4/site-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
TypeError: neib_shape[0]=3, neib_step[0]=1 and ten4.shape[2]=2 not consistent
Apply node that caused the error: Images2Neibs{valid}(Elemwise{Composite{(i0 * (Abs(i1) + i2 + i3))}}[(0, 2)].0, TensorConstant{(2,) of 3}, TensorConstant{(2,) of 1})
Toposort index: 165
Inputs types: [TensorType(float32, 4D), TensorType(int64, vector), TensorType(int64, vector)]
Inputs shapes: [(1, 512, 2, 2), (2,), (2,)]
Inputs strides: [(8192, 16, 8, 4), (8,), (8,)]
Inputs values: ['not shown', array([3, 3]), array([1, 1])]
Outputs clients: [[Reshape{4}(Images2Neibs{valid}.0, MakeVector{dtype='int64'}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "doodle.py", line 555, in <module>
    generator.run()
  File "doodle.py", line 508, in run
    self.prepare_optimization()
  File "doodle.py", line 359, in prepare_optimization
    self.losses = self.content_loss() + self.style_loss() + self.total_variation_loss()
  File "doodle.py", line 403, in style_loss
    + [self.model.tensor_outputs['map'+l] for l in self.style_layers])
  File "doodle.py", line 343, in extract_patches
    patches = theano.tensor.nnet.neighbours.images2neibs(f, (size, size), (stride, stride), mode='valid')

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by alexjc** [comment]
Try making your image a multiple of 16 or 32. In general it seems a bit too small... Do you have a higher resolution version?

**Comment by alexjc** [comment]
I think this is similar to #74.

**Comment by doktorstick** [comment]
There must be a minimum size on the sample images, even if a multiple of 8, 16, or 32. I tried the following with the docker install on OSX:
```
$ doodle --style samples/dirt.png --output new-dirt.png --seed=noise --seed-range=192:255 --iterations=50 --phases=3 --output-size=1280x256
```
with `dirt.png` being 64x64, 64x128, 64x256, 64x320 and the flipped dimensions (e.g., 320x64). I also dropped the `--output-size` thinking it may help. No luck.

Once I grabbed a large image (1280x256) then it worked. I didn't try to narrow down the line between failure and success.

**Comment by carterbox** [comment]
This problem is definitely related to the patches trying to be extracted from any resolution smaller than 64p in one dimension. I don't understand why though, because the patches are only 3x3, I would expect that there wouldn't be problems until the resolution dropped down to 4x4.
