### ISSUE TITLE
KeyError: 'conv4_2' when trying to use a content image

### ISSUE THREAD

**Issue by nshaud** [alexjc/neural-doodle#9]
When I try to specify a content image and map using the following command :
```
python3 doodle.py --style samples/input.jpg --content samples/content.jpg --output samples/output.png --device=gpu0 --iterations=80
```
it results in a Key Error exception.

```
Neural Doodle for semantic style transfer.
~/src/neural-doodle/venv/lib/python3.4/site-packages/theano/tensor/signal/downsample.py:5: UserWarning: downsample module has been moved to the pool module.
  warnings.warn("downsample module has been moved to the pool module.")
  - Loading content image data from samples/input.jpg.
  - Loading content semantic map from samples/input_sem.png.
  - Loading style image data from samples/content.jpg.
  - Loading style semantic map from samples/content_sem.png.

Phase #0: resolution 75x75  scale 0.25
  - Style layer sem3_1: 256 patches in 599kb.
  - Style layer sem4_1: 49 patches in 227kb.
Traceback (most recent call last):
  File "doodle.py", line 462, in <module>
    generator.run()
  File "doodle.py", line 428, in run
    self.prepare_optimization()
  File "doodle.py", line 295, in prepare_optimization
    self.losses = self.content_loss() + self.style_loss() + self.total_variation_loss()
  File "doodle.py", line 318, in content_loss
    [self.model.tensor_outputs['conv'+l] for l in self.content_layers])
  File "doodle.py", line 318, in <listcomp>
    [self.model.tensor_outputs['conv'+l] for l in self.content_layers])
KeyError: 'conv4_2'
```

I tried specifying another layer with the ```--content-layers=4_1``` switch, but it resulted in another error:
```
Phase #0: resolution 75x75  scale 0.25
  - Style layer sem3_1: 256 patches in 599kb.
  - Style layer sem4_1: 49 patches in 227kb.
Traceback (most recent call last):
  File "doodle.py", line 462, in <module>
    generator.run()
  File "doodle.py", line 428, in run
    self.prepare_optimization()
  File "doodle.py", line 295, in prepare_optimization
    self.losses = self.content_loss() + self.style_loss() + self.total_variation_loss()
  File "doodle.py", line 322, in content_loss
    for l in zip(layers, result):
NameError: name 'layers' is not defined
```

**Comment by alexjc** [comment]
OK, that was a refactoring bug I introduced when documenting everything. Didn't test with content images. Thanks for reporting!
