### ISSUE TITLE
AWS attempt 

### ISSUE THREAD

**Issue by DrewWham** [alexjc/neural-doodle#92]
Will this run on a g2.2xlarge instance?
I attempted a docker image install, everything looked good till:

Neural Doodle for semantic style transfer.
Traceback (most recent call last):
  File "doodle.py", line 85, in <module>
    import theano
  File "/usr/local/lib/python3.4/dist-packages/theano/__init__.py", line 103, in <module>
    import theano.sandbox.cuda
  File "/usr/local/lib/python3.4/dist-packages/theano/sandbox/cuda/__init__.py", line 697, in <module>
    use(device=config.device, force=config.force_device, test_driver=False)
  File "/usr/local/lib/python3.4/dist-packages/theano/sandbox/cuda/__init__.py", line 495, in use
    device, cuda_initialization_error_message))
OSError: You forced the use of gpu device gpu0, but CUDA initialization failed with error:
Unable to get the number of gpus available: CUDA driver version is insufficient for CUDA runtime version

Any guidance would be appreciated, or if there is an AMI someone could point me to that would be great too. I found an AMI with an older version but I'd like to try the new options that are available.

**Comment by DrewWham** [comment]
Did some more research, looks like this is attributable to the communication between the GPU and stuff running through docker. I've attempted several fixes by following documentation from NVIDIA's docker page but I still run into the same error here. Am I doing things in the wrong order? My approaches have been:

1) start g2.2xlarge instance (I've tried ami-f4956399 which says it has NVIDIA docker already and ami-981715f2 which has an old neural-doodle, and I installed docker)

2) start docker, run "Hello World" and observe that it is working

3) run the code from 2.a on the neural-doodle installation guide and observe installation as it appears in the box above that code and observe that $ doodle --help returned correct output.

4) attempt the example neural doodle and I get the above output.

Clearly I'm not doing something correctly at the NVIDIA docker step but I can't figure out what. It may be an obvious error, if someone could point me in the correct direction I'd be grateful

**Comment by alexjc** [comment]
Seems there's a version mismatch between the docker instance and the driver. The hint is this line:
```
CUDA driver version is insufficient for CUDA runtime version
```
Not sure which is easier to fix. You can edit the scripts in `docker` and change the version of CUDA to install, or update your AMI?

**Comment by DrewWham** [comment]
Thanks Alex for your reply. Indeed, that looks like that is the issue. I've started several AMIs that have Docker and CUDA but the best I can find is V7.5.17, looks like the Docker file uses v7.5.18. 

I forked Neural Doodle and edited my fork to point to v7.5.17 in the Docker file but it looks like 

alias doodle="docker run -v $(pwd)/samples:/nd/samples -v $(pwd)/frames:/nd/frames \
                         -it alexjc/neural-doodle:gpu"

points toward your docker hub, how do I fork the docker hub so I can point my docker run to my Neural Doodle fork? I messed around on the docker site but I don't see how to do something similar to a fork from there.

If you have any advice or direction I'd be grateful, I'll keep messing with it till I figure it out. Seems like I'm close.

**Comment by alexjc** [comment]
You should rebuild it locally, try this in the current folder:
```docker build -f docker-gpu.df .```

**Comment by hholst80** [comment]
Also, have you verified that the TF version compiled into the docker image have support for the compute capability of the AWS node? The cards are a bit older model...

**Comment by alexjc** [comment]
@hholst80 I haven't tested on AWS. TF is not used, just Theano. As long as CUDA works it shouldn't matter.
