### ISSUE TITLE
Running example from README on OSX causes crash

### ISSUE THREAD

**Issue by kirilledelman** [alexjc/neural-doodle#93]
Hi,
Thanks for sharing your code with us!

I'm trying to run the example from README and get a crash after a couple minutes before it can finish

```
python3 doodle.py --style samples/Monet.jpg --output samples/Coastline.png                   --device=cpu --iterations=40
Neural Doodle for semantic style transfer.
  - Using device `cpu` for processing the images.
  - Adding `samples/Coastline_sem.png` as semantic map.
  - Loading `samples/Monet.jpg` for style data.
  - Adding `samples/Monet_sem.png` as semantic map.

Phase #0: resolution 128x96  scale 0.25
  - Style layer 3_1: (660, 259, 3, 3) patches in 1,538kb.
  - Style layer 4_1: (140, 515, 3, 3) patches in 648kb.

Traceback (most recent call last):
  File "doodle.py", line 658, in <module>
    generator.run()
  File "doodle.py", line 635, in run
    iprint=-1)                       # Handle our own logging of information.
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/optimize/lbfgsb.py", line 193, in fmin_l_bfgs_b
    **opts)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/optimize/lbfgsb.py", line 330, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/optimize/lbfgsb.py", line 278, in func_and_grad
    f = fun(x, *args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 289, in function_wrapper
    return function(*(wrapper_args + args))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 63, in __call__
    fg = self.fun(x, *args)
  File "doodle.py", line 536, in evaluate
    best_idx = self.evaluate_slices(f, l)
  File "doodle.py", line 504, in evaluate_slices
    layer.W.set_value(weights)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/theano/compile/sharedvalue.py", line 127, in set_value
    self.container.value = copy.deepcopy(new_value)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/theano/gof/link.py", line 479, in __set__
    self.storage[0] = self.type.filter(value, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/theano/tensor/type.py", line 195, in filter
    " dimension.", data.shape, self.broadcastable)
TypeError: ('Non-unit value on shape on a broadcastable dimension.', (330, 259, 3, 3), (True, False, False, False), 'Container name "None"')
```

Any clues what could be wrong? I installed the "bleeding edge" versions of Theano and Lasagne.

**Comment by alexjc** [comment]
@kirilledelman Did you find out what it was? If so, please post here so the next person can find it too!

**Comment by kirilledelman** [comment]
@alexjc 

I reinstalled Theano and Lasagne to the current version ( not "bleeding edge" ) and this error disappeared. I was able to get the result in README example.
