### ISSUE TITLE
Non-unit value on shape on a broadcastable dimension error

### ISSUE THREAD

**Issue by kirilledelman** [alexjc/neural-doodle#94]
Hi,

I'm having odd issues when trying to use doodle on my first attempt at my own images.

Both, style and content sizes are 512x512

style.jpg:
![style](https://cloud.githubusercontent.com/assets/6539713/16809995/e3f95f78-48e7-11e6-9022-f122e542997f.jpg)
style_sem.png:
![style_sem](https://cloud.githubusercontent.com/assets/6539713/16809999/e9c06dd4-48e7-11e6-96d2-6a468b738427.png)

content.png:
![niko](https://cloud.githubusercontent.com/assets/6539713/16810018/029babfc-48e8-11e6-9cf9-560d9b36eaee.png)
content_sem.png:
![niko_sem](https://cloud.githubusercontent.com/assets/6539713/16810035/0d776bce-48e8-11e6-9a89-afe6b84c105c.png)

Running:
`python3 doodle.py --style style.jpg --content content.png --iterations=20`

Starts up, and then dies:
```
Neural Doodle for semantic style transfer.
  - Using device `cpu` for processing the images.
  - Loading `niko.png` for content data.
  - Adding `niko_sem.png` as semantic map.
  - Loading `style.jpg` for style data.
  - Adding `style_sem.png` as semantic map.

Phase #0: resolution 128x128  scale 0.25
  - Style layer 3_1: (900, 259, 3, 3) patches in 2,097kb.
  - Style layer 4_1: (196, 515, 3, 3) patches in 908kb.
  - Content layer conv4_2: 512 features in 131kb.

Traceback (most recent call last):
  File "doodle.py", line 658, in <module>
    generator.run()
  File "doodle.py", line 635, in run
    iprint=-1)                       # Handle our own logging of information.
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/optimize/lbfgsb.py", line 193, in fmin_l_bfgs_b
    **opts)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/optimize/lbfgsb.py", line 330, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/optimize/lbfgsb.py", line 278, in func_and_grad
    f = fun(x, *args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 289, in function_wrapper
    return function(*(wrapper_args + args))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 63, in __call__
    fg = self.fun(x, *args)
  File "doodle.py", line 536, in evaluate
    best_idx = self.evaluate_slices(f, l)
  File "doodle.py", line 504, in evaluate_slices
    layer.W.set_value(weights)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/theano/compile/sharedvalue.py", line 127, in set_value
    self.container.value = copy.deepcopy(new_value)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/theano/gof/link.py", line 479, in __set__
    self.storage[0] = self.type.filter(value, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/theano/tensor/type.py", line 195, in filter
    " dimension.", data.shape, self.broadcastable)
TypeError: ('Non-unit value on shape on a broadcastable dimension.', (450, 259, 3, 3), (True, False, False, False), 'Container name "None"')
```

Any ideas?

**Comment by alexjc** [comment]
It may be an installation problem, see #93 that was just resolved?

**Comment by kirilledelman** [comment]
No, fixing the installation problem allowed me to successfully run the example included in the download. But I'm now getting this error with my own files.

**Comment by alexjc** [comment]
Hmm, does it work without the semantic maps?

**Comment by kirilledelman** [comment]
@alexjc This seems relevant, although I know nothing about this framework:

https://github.com/Lasagne/Lasagne/issues/692

**Comment by alexjc** [comment]
@kirilledelman I'm not sure it's related, we don't use `scan`. Does your setup work with other example images, or without the semantic maps? Wondering if it's constant or dependent on the source.

**Comment by htoyryla** [comment]
Although it might not be related, I got this error message too when I had to reinstall neural-doodle, see https://github.com/alexjc/neural-doodle/issues/89 at the end. I found out that pip installed the newest lasagne instead of the specific commit that was given. I got it working by cloning lasagne, reverting it to the specific commit and then installing it by pip.

**Comment by kirilledelman** [comment]
@htoyryla Thanks for your suggestion, I'll give it a try!

**Comment by kirilledelman** [comment]
For those having the same problem, I've downgraded Lasagne by uninstalling, then installing an older commit, which seems to have fixed the problem:

`pip3 uninstall Lasagne`
`pip3 install git+git://github.com/Lasagne/Lasagne.git@31ac7d2bbcb4777b9a500b`

Thanks to @htoyryla for this!

**Comment by alexjc** [comment]
Thanks for reporting the fix! I wonder if/how we can correctly specify Lasagne's version in `requirements.txt`.

**Comment by weiliu620** [comment]
Had the same problem and followed the suggestion and downgraded lasagne and got rid of the error. Thanks @kirilledelman

**Comment by ArthurZC23** [comment]
I also ran in the same problem. Thank you for your help @kirilledelman.

**Comment by askerlee** [comment]
I encountered the same error and figured out the root by comparing my environment with the docker image.
In the newer version of Lasagne (although labeled as 0.2.dev1, the same as the version used in the docker image),  the parameter initialization code of the conv layer is somewhat different. 
lasagne/utils.py:create_param():
```
        bcast = tuple(s == 1 for s in shape)
        spec = theano.shared(spec, broadcastable=bcast)
```
doodle.py creates a few layers using this configuration:
`net['nn'+suffix] = ConvLayer(net['dup'+suffix], 1, 3, b=None, pad=0, flip_filters=False)`
You can see the number of filters is 1, which is also the size of the first dimension of layer.W. So the layer.W has a shape like (1, 65, 3, 3). Then the above initialization code will set the first dimension of W as broadcastable. A broadcastable dimension will raise error when its size is being changed in layer.W.set_value(weights).

The workaround without downgrading lasagne is to set all dimensions of layer.W as non-broadcastable:
```
            net['nn'+suffix] = ConvLayer(net['dup'+suffix], 1, 3, b=None, pad=0, flip_filters=False)
+            shape = net['nn'+suffix].W.get_value().shape
+            net['nn'+suffix].W = theano.shared( net['nn'+suffix].W.get_value(), broadcastable=[False]* len(shape) )
```

**Comment by Saycka** [comment]
I try to use this
```
+           shape = net['nn'+suffix].W.get_value().shape
+           net['nn'+suffix].W = theano.shared( net['nn'+suffix].W.get_value(), broadcastable=[False]* len(shape) )
```
but I have a error:

```
Neural Doodle for semantic style transfer.
  - Using device `cpu` for processing the images.
  - Adding `samples/Landscape_sem.png` as semantic map.
  - Loading `samples/Renoir.jpg` for style data.
  - Adding `samples/Renoir_sem.png` as semantic map.
Traceback (most recent call last):
  File "doodle.py", line 661, in <module>
    generator = NeuralGenerator()
  File "doodle.py", line 281, in __init__
    self.model = Model()
  File "doodle.py", line 112, in __init__
    self.setup_model()
  File "doodle.py", line 160, in setup_model
    shape = net['nn'+suffix].W.get_value().shape
KeyError: 'nn1_1'
```



the code with 160 row:

```
    def setup_model(self, input=None):
        """Use lasagne to create a network of convolution layers, first using VGG19 as the framework
        and then adding augmentations for Semantic Style Transfer.
        """
        net, self.channels = {}, {}

        # Primary network for the main image. These are convolution only, and stop at layer 4_2 (rest unused).
        net['img']     = input or InputLayer((None, 3, None, None))
        net['conv1_1'] = ConvLayer(net['img'],     64, 3, pad=1)
        net['conv1_2'] = ConvLayer(net['conv1_1'], 64, 3, pad=1)
        net['pool1']   = PoolLayer(net['conv1_2'], 2, mode='average_exc_pad')
        net['conv2_1'] = ConvLayer(net['pool1'],   128, 3, pad=1)
        net['conv2_2'] = ConvLayer(net['conv2_1'], 128, 3, pad=1)
        net['pool2']   = PoolLayer(net['conv2_2'], 2, mode='average_exc_pad')
        net['conv3_1'] = ConvLayer(net['pool2'],   256, 3, pad=1)
        net['conv3_2'] = ConvLayer(net['conv3_1'], 256, 3, pad=1)
        net['conv3_3'] = ConvLayer(net['conv3_2'], 256, 3, pad=1)
        net['conv3_4'] = ConvLayer(net['conv3_3'], 256, 3, pad=1)
        net['pool3']   = PoolLayer(net['conv3_4'], 2, mode='average_exc_pad')
        net['conv4_1'] = ConvLayer(net['pool3'],   512, 3, pad=1)
        net['conv4_2'] = ConvLayer(net['conv4_1'], 512, 3, pad=1)
        net['conv4_3'] = ConvLayer(net['conv4_2'], 512, 3, pad=1)
        net['conv4_4'] = ConvLayer(net['conv4_3'], 512, 3, pad=1)
        net['pool4']   = PoolLayer(net['conv4_4'], 2, mode='average_exc_pad')
        net['conv5_1'] = ConvLayer(net['pool4'],   512, 3, pad=1)
        net['conv5_2'] = ConvLayer(net['conv5_1'], 512, 3, pad=1)
        net['conv5_3'] = ConvLayer(net['conv5_2'], 512, 3, pad=1)
        net['conv5_4'] = ConvLayer(net['conv5_3'], 512, 3, pad=1)
        net['main']    = net['conv5_4']

        # Auxiliary network for the semantic layers, and the nearest neighbors calculations.
        net['map'] = InputLayer((1, 1, None, None))
        for j, i in itertools.product(range(5), range(4)):
            if j < 2 and i > 1: continue
            suffix = '%i_%i' % (j+1, i+1)

            if i == 0:
                net['map%i'%(j+1)] = PoolLayer(net['map'], 2**j, mode='average_exc_pad')
            self.channels[suffix] = net['conv'+suffix].num_filters
            
```
            if args.semantic_weight > 0.0:
                net['sem'+suffix] = ConcatLayer([net['conv'+suffix], net['map%i'%(j+1)]])
            else:
                net['sem'+suffix] = net['conv'+suffix]

            shape = net['nn'+suffix].W.get_value().shape
            net['nn'+suffix].W = theano.shared( net['nn'+suffix].W.get_value(), broadcastable=[False]* len(shape) )
            net['dup'+suffix] = InputLayer(net['sem'+suffix].output_shape)
            net['nn'+suffix] = ConvLayer(net['dup'+suffix], 1, 3, b=None, pad=0, flip_filters=False)

        self.network = net

**Comment by htoyryla** [comment]
Looks like 160 refers to wrong line in the latest version? 

I would try to move the inserted lines after the line in which net['nn'+suffix] gets assigned. Like this:

```
        net['dup'+suffix] = InputLayer(net['sem'+suffix].output_shape)
        net['nn'+suffix] = ConvLayer(net['dup'+suffix], 1, 3, b=None, pad=0, flip_filters=False)
        shape = net['nn'+suffix].W.get_value().shape
        net['nn'+suffix].W = theano.shared( net['nn'+suffix].W.get_value(), broadcastable=[False]* len(shape) )
```

This should at least avoid the key error. If there is a deeper problem then I cannot help. Don't even have a working theano/lasagne installation these days.
